version: '3'

services:     
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:2023.1.2
    restart: always
    privileged: true
    volumes:
      - ./home-assistant/config:/config
    network_mode: host
    environment:
      - TZ=Europe/Moscow
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:1.6.8
    network_mode: host
    restart: always
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/conf.d:/mosquitto/conf.d
      - ./mqtt/ssl:/mosquitto/ssl
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    network_mode: host
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  node-exporter:
    container_name: node-exporter
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
  grafana:
    container_name: grafana
    image: grafana/grafana
    user: root
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    hostname: grafana
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: "Europe/Moscow"