- id: '1673625388028'
  alias: Тестируем автоматизации
  description: ''
  trigger:
  - platform: device
    device_id: 0cb37eb73d6a60a6136ed5aa84bcf93a
    domain: device_tracker
    entity_id: device_tracker.redmi_note_9_pro
    type: enters
    zone: zone.home
  condition:
  - condition: device
    device_id: 0cb37eb73d6a60a6136ed5aa84bcf93a
    domain: device_tracker
    entity_id: device_tracker.redmi_note_9_pro
    type: is_home
  action:
  - device_id: ad14d6cb80fd1ff3283d221051b951d6
    domain: mobile_app
    type: notify
    message: Я дома мать!
    title: Куку
  mode: single
